# Generated by Django 4.1.3 on 2022-12-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_profile_city_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data_ordered',
        ),
    ]
