<<<<<<< HEAD
# Generated by Django 4.1.3 on 2022-12-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_order_data_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=200, null=True),
        ),
    ]
=======
# Generated by Django 4.1.3 on 2022-12-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_order_data_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=200, null=True),
        ),
    ]
>>>>>>> 550c397da82c84627a5a585ea40baaaeb7077ad9
