# Generated by Django 4.1.3 on 2022-12-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_orderitem_status_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.service'),
        ),
    ]
