# Generated by Django 4.1.3 on 2022-12-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_order_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
    ]
