# Generated by Django 4.1.3 on 2022-12-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_orderitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='digital',
        ),
    ]
