# Generated by Django 4.1.3 on 2023-01-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_service_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
    ]
